import {useState} from 'react';import {Trash2} from 'lucide-react'
import CostCard from '../components/CostCard';import {services,defaultRows,rowCost,usd,useLS,palette,price} from '../data/awsServices';import {CostRow} from '../types/cloud'
export default function Costs(){const [rows,setRows]=useLS<CostRow[]>('cloudops-costs',defaultRows);const [svc,setSvc]=useState('EC2');const [qty,setQty]=useState(1);const [h,setH]=useState(730)
const m=rows.reduce((a,r)=>a+rowCost(r),0);let acc=0
const grad=rows.map((r,i)=>{const s=acc;acc+=m?rowCost(r)/m*100:0;return `${palette[i%7]} ${s}% ${acc}%`}).join(',')
return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><CostCard label="Costo estimado de la selección" value={usd(price(svc)*qty*h)}/><CostCard label="Costo mensual" value={usd(m)}/><CostCard label="Costo anual" value={usd(m*12)}/></div>
<div className="card flex flex-wrap items-end gap-3">{[['Servicio',<select className="inp" value={svc} onChange={e=>setSvc(e.target.value)}>{services.map(s=><option key={s.id}>{s.id}</option>)}</select>],['Cantidad',<input type="number" min={1} className="inp" value={qty} onChange={e=>setQty(+e.target.value)}/>],['Horas estimadas / mes',<input type="number" min={1} max={744} className="inp" value={h} onChange={e=>setH(+e.target.value)}/>]].map(([l,c],i)=><label key={i} className="min-w-[140px] flex-1 text-sm font-medium">{l as string}<div className="mt-1">{c}</div></label>)}<button className="btn" onClick={()=>setRows([...rows,{id:Date.now(),service:svc,qty,hours:h}])}>Agregar al cálculo</button></div>
<div className="grid gap-6 lg:grid-cols-3"><div className="card overflow-x-auto lg:col-span-2"><table className="w-full text-left text-sm"><thead className="text-mute"><tr><th className="py-2">Servicio</th><th>Cant.</th><th>Horas</th><th>Mensual</th><th>Anual</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-line"><td className="py-2 font-medium">{r.service}</td><td>{r.qty}</td><td>{r.hours}</td><td>{usd(rowCost(r))}</td><td>{usd(rowCost(r)*12)}</td><td><button aria-label="Eliminar" onClick={()=>setRows(rows.filter(x=>x.id!==r.id))}><Trash2 size={16} className="text-alert"/></button></td></tr>)}</tbody></table></div>
<div className="card"><h2 className="mb-4 text-lg font-semibold">Distribución de costos</h2><div className="mx-auto h-40 w-40 rounded-full" style={{background:m?`conic-gradient(${grad})`:'#E2E8F0',mask:'radial-gradient(circle,transparent 45%,#000 46%)',WebkitMask:'radial-gradient(circle,transparent 45%,#000 46%)'}}/><ul className="mt-4 space-y-1 text-sm">{rows.map((r,i)=><li key={r.id} className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:palette[i%7]}}/>{r.service}<span className="ml-auto text-mute">{m?(rowCost(r)/m*100).toFixed(0):0}%</span></li>)}</ul></div></div></div>}
