import {useState} from 'react';import {Search,MapPin,Activity,Server,Layers} from 'lucide-react'
import RegionCard,{stLabel} from '../components/RegionCard';import WorldMap from '../components/WorldMap';import StatCard from '../components/StatCard';import StatusBadge from '../components/StatusBadge';import {regions,useLS} from '../data/awsServices'
const groups=['Todas','Norteamérica','Sudamérica','Europa','Asia Pacífico']
export default function Infrastructure(){const [sel,setSel]=useLS('cloudops-region','us-east-1');const [g,setG]=useState('Todas');const [q,setQ]=useState('')
const list=regions.filter(r=>(g==='Todas'||r.loc===g)&&(r.name+r.code+r.country+r.services.join(' ')).toLowerCase().includes(q.toLowerCase()))
const cur=regions.find(r=>r.code===sel)??regions[0]
return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
<StatCard label="Región principal" value={cur.code} icon={<MapPin size={20}/>}/><StatCard label="Estado regional" value={stLabel[cur.status]} icon={<Activity size={20}/>} color={cur.status==='ok'?'#16A34A':cur.status==='warn'?'#F59E0B':'#DC2626'}/>
<StatCard label="Servicios desplegados" value={String(cur.services.length)} icon={<Server size={20}/>}/><StatCard label="Zonas de disponibilidad" value={String(cur.zones)} icon={<Layers size={20}/>}/></div>
<div className="grid gap-6 lg:grid-cols-3"><div className="card space-y-4 lg:col-span-2"><div><h2 className="text-lg font-semibold">Mapa de regiones AWS</h2><p className="text-xs text-mute">Selecciona una región para ver su detalle. {list.length} de {regions.length} visibles.</p></div>
<div className="flex flex-wrap gap-3"><div className="relative min-w-[200px] flex-1"><Search size={16} className="absolute left-3 top-3 text-mute"/><input className="inp pl-9" placeholder="Buscar región, ciudad o servicio" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="flex flex-wrap gap-1.5">{groups.map(x=><button key={x} onClick={()=>setG(x)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${g===x?'bg-brand text-white':'border border-line text-mute hover:bg-bg'}`}>{x}</button>)}</div></div>
<WorldMap all={regions} list={list} sel={sel} onSelect={setSel}/>
<div className="flex flex-wrap gap-4 text-xs text-mute">{(['ok','warn','error'] as const).map(k=><span key={k} className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full" style={{background:{ok:'#16A34A',warn:'#F59E0B',error:'#DC2626'}[k]}}/>{k==='error'?'Mantenimiento programado':stLabel[k]}</span>)}</div></div>
<aside className="rounded-2xl bg-side p-5 text-white"><p className="text-xs text-slate-400">Región seleccionada</p><h2 className="mt-2 text-2xl font-bold">{cur.code}</h2><p className="text-sm text-slate-300">{cur.name}</p><p className="text-xs text-slate-400">{cur.country}</p><div className="mt-3"><StatusBadge status={cur.status} label={stLabel[cur.status]}/></div>
<div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-800 p-3"><p className="text-xs text-slate-400">Zonas</p><p className="text-xl font-bold">{cur.zones}</p></div><div className="rounded-xl bg-slate-800 p-3"><p className="text-xs text-slate-400">Ubicaciones de borde</p><p className="text-xl font-bold">{cur.edge}</p></div></div>
<p className="mt-5 text-xs text-slate-400">Servicios de la propuesta</p><div className="mt-2 flex flex-wrap gap-1.5">{cur.services.map(s=><span key={s} className="rounded bg-slate-700 px-2 py-0.5 text-xs">{s}</span>)}</div><p className="mt-5 text-xs text-slate-400">Esta región se usa como región seleccionada en el Dashboard.</p></aside></div>
<div><h2 className="mb-3 text-lg font-semibold">Regiones disponibles</h2>{list.length===0?<p className="card text-sm text-mute">Ninguna región coincide. Cambia el filtro o la búsqueda.</p>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{list.map(r=><RegionCard key={r.code} r={r} active={r.code===sel} onSelect={()=>setSel(r.code)}/>)}</div>}</div></div>}
